Build with jdk8 due to SSL error downloading gradle
Travis reports:

Downloading https://services.gradle.org/distributions/gradle-4.0-bin.zip

Exception in thread "main" javax.net.ssl.SSLException:
java.security.ProviderException: java.security.InvalidKeyException: EC
parameters error